parameters:
  azureSub: ""
  env: ""
  pipeline: current
  version: ""
  reset_db: no

jobs:
  - job: DB
    displayName: Deploy DB to ${{parameters.env}}

    variables:
      database-server: dfta-db-${{parameters.env}}.postgres.database.azure.com
      database-name: kleecontrib_dfta
      ${{if eq(parameters.pipeline, 'current')}}:
        workingDirectory: $(Pipeline.Workspace)/DB
      ${{else}}:
        workingDirectory: $(Pipeline.Workspace)/${{parameters.pipeline}}/DB

    pool: klee-focus-dfta-pool
    workspace:
      clean: all

    steps:
      - checkout: none

      - task: UseDotNet@2
        displayName: .NET 10
        inputs:
          version: 10.x

      - task: AzureCLI@2
        displayName: Get Azure PGSQL Credentials
        inputs:
          addSpnToEnvironment: true
          scriptType: bash
          azureSubscription: ${{parameters.azureSub}}
          scriptLocation: inlineScript
          inlineScript: |
            echo "##vso[task.setvariable variable=database-admin-userid]$(az ad sp show --id $servicePrincipalId --query [displayName][0] -o tsv)"
            echo "##vso[task.setvariable variable=database-admin-secret;issecret=true]$(az account get-access-token --resource-type oss-rdbms --query '[accessToken]' -o tsv)"

      - download: ${{parameters.pipeline}}
        displayName: Download DB
        artifact: DB

      - script: chmod u+x KleeContrib.Dfta.Migrations && ./KleeContrib.Dfta.Migrations --reset ${{parameters.reset_db}}
        displayName: Run Migrations
        workingDirectory: $(workingDirectory)
        env:
          Database__Server: $(database-server)
          Database__Database: $(database-name)
          Database__User_Id: $(database-admin-userid)
          Database__Password: $(database-admin-secret)
          AppUserId: dfta-api-${{parameters.env}}
