// <auto-generated />
using System;
using KleeContrib.Dfta.Clients.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KleeContrib.Dfta.Migrations.Migrations
{
    [DbContext(typeof(KleeContribDftaDbContext))]
    [Migration("20251022154132_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KleeContrib.Dfta.Clients.Db.Common.Models.Traduction", b =>
                {
                    b.Property<string>("ResourceKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trd_resource_key");

                    b.Property<string>("Locale")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trd_locale");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trd_label");

                    b.HasKey("ResourceKey", "Locale");

                    b.HasIndex("ResourceKey");

                    b.ToTable("traductions");

                    b.HasData(
                        new
                        {
                            ResourceKey = "securite.droit.values.Create",
                            Locale = "fr-FR",
                            Label = "Création"
                        },
                        new
                        {
                            ResourceKey = "securite.droit.values.Delete",
                            Locale = "fr-FR",
                            Label = "Suppression"
                        },
                        new
                        {
                            ResourceKey = "securite.droit.values.Read",
                            Locale = "fr-FR",
                            Label = "Lecture"
                        },
                        new
                        {
                            ResourceKey = "securite.droit.values.Update",
                            Locale = "fr-FR",
                            Label = "Mise à jour"
                        },
                        new
                        {
                            ResourceKey = "securite.typeDroit.values.Admin",
                            Locale = "fr-FR",
                            Label = "Administration"
                        },
                        new
                        {
                            ResourceKey = "securite.typeDroit.values.Read",
                            Locale = "fr-FR",
                            Label = "Lecture"
                        },
                        new
                        {
                            ResourceKey = "securite.typeDroit.values.Write",
                            Locale = "fr-FR",
                            Label = "Ecriture"
                        },
                        new
                        {
                            ResourceKey = "securite.typeUtilisateur.values.Admin",
                            Locale = "fr-FR",
                            Label = "Administrateur"
                        },
                        new
                        {
                            ResourceKey = "securite.typeUtilisateur.values.Client",
                            Locale = "fr-FR",
                            Label = "Client"
                        },
                        new
                        {
                            ResourceKey = "securite.typeUtilisateur.values.Gestionnaire",
                            Locale = "fr-FR",
                            Label = "Gestionnaire"
                        },
                        new
                        {
                            ResourceKey = "securite.droit.values.Create",
                            Locale = "en-US",
                            Label = "Create"
                        },
                        new
                        {
                            ResourceKey = "securite.droit.values.Delete",
                            Locale = "en-US",
                            Label = "Delete"
                        },
                        new
                        {
                            ResourceKey = "securite.droit.values.Read",
                            Locale = "en-US",
                            Label = "Read"
                        },
                        new
                        {
                            ResourceKey = "securite.droit.values.Update",
                            Locale = "en-US",
                            Label = "Update"
                        },
                        new
                        {
                            ResourceKey = "securite.typeDroit.values.Admin",
                            Locale = "en-US",
                            Label = "Admin"
                        },
                        new
                        {
                            ResourceKey = "securite.typeDroit.values.Read",
                            Locale = "en-US",
                            Label = "Read"
                        },
                        new
                        {
                            ResourceKey = "securite.typeDroit.values.Write",
                            Locale = "en-US",
                            Label = "Write"
                        },
                        new
                        {
                            ResourceKey = "securite.typeUtilisateur.values.Admin",
                            Locale = "en-US",
                            Label = "Administrator"
                        },
                        new
                        {
                            ResourceKey = "securite.typeUtilisateur.values.Client",
                            Locale = "en-US",
                            Label = "Client"
                        },
                        new
                        {
                            ResourceKey = "securite.typeUtilisateur.values.Gestionnaire",
                            Locale = "en-US",
                            Label = "Manager"
                        });
                });

            modelBuilder.Entity("KleeContrib.Dfta.Clients.Db.Securite.Models.DroitProfil", b =>
                {
                    b.Property<string>("DroitCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dro_code");

                    b.Property<int>("ProfilId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_id");

                    b.HasKey("DroitCode", "ProfilId");

                    b.HasIndex("ProfilId");

                    b.ToTable("droit_profils");

                    b.HasData(
                        new
                        {
                            DroitCode = "CREATE",
                            ProfilId = 1
                        },
                        new
                        {
                            DroitCode = "READ",
                            ProfilId = 2
                        },
                        new
                        {
                            DroitCode = "UPDATE",
                            ProfilId = 3
                        },
                        new
                        {
                            DroitCode = "DELETE",
                            ProfilId = 4
                        });
                });

            modelBuilder.Entity("KleeContrib.Dfta.Clients.Db.Securite.Models.Profil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pro_date_creation");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pro_date_modification");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pro_libelle");

                    b.HasKey("Id");

                    b.ToTable("profils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 631, DateTimeKind.Utc).AddTicks(7622),
                            Libelle = "Profil 1"
                        },
                        new
                        {
                            Id = 2,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 631, DateTimeKind.Utc).AddTicks(7755),
                            Libelle = "Profil 2"
                        },
                        new
                        {
                            Id = 3,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 631, DateTimeKind.Utc).AddTicks(7756),
                            Libelle = "Profil 3"
                        },
                        new
                        {
                            Id = 4,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 631, DateTimeKind.Utc).AddTicks(7760),
                            Libelle = "Profil 4"
                        });
                });

            modelBuilder.Entity("KleeContrib.Dfta.Clients.Db.Securite.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("uti_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("uti_actif");

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uti_adresse");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uti_date_creation");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uti_date_modification");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("uti_date_naissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uti_email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uti_nom");

                    b.Property<string>("NomFichierPhoto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uti_nom_fichier_photo");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uti_prenom");

                    b.Property<int>("ProfilId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_id");

                    b.Property<string>("TypeUtilisateurCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tut_code");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfilId");

                    b.HasIndex("TypeUtilisateurCode");

                    b.ToTable("utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 631, DateTimeKind.Utc).AddTicks(9945),
                            Email = "test1@test.com",
                            Nom = "Jean",
                            Prenom = "Michel",
                            ProfilId = 1,
                            TypeUtilisateurCode = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 632, DateTimeKind.Utc).AddTicks(68),
                            Email = "test2@test.com",
                            Nom = "Gerard",
                            Prenom = "Jugnos",
                            ProfilId = 2,
                            TypeUtilisateurCode = "GEST"
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 632, DateTimeKind.Utc).AddTicks(72),
                            Email = "test3@test.com",
                            Nom = "Gad",
                            Prenom = "El",
                            ProfilId = 3,
                            TypeUtilisateurCode = "CLIENT"
                        },
                        new
                        {
                            Id = 4,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 632, DateTimeKind.Utc).AddTicks(74),
                            Email = "test4@test.com",
                            Nom = "Bernard",
                            Prenom = "Bruno",
                            ProfilId = 4,
                            TypeUtilisateurCode = "ADMIN"
                        },
                        new
                        {
                            Id = 5,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 632, DateTimeKind.Utc).AddTicks(76),
                            Email = "test5@test.com",
                            Nom = "Sisi",
                            Prenom = "Brindacier",
                            ProfilId = 1,
                            TypeUtilisateurCode = "GEST"
                        },
                        new
                        {
                            Id = 6,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 632, DateTimeKind.Utc).AddTicks(78),
                            Email = "test6@test.com",
                            Nom = "Bibi",
                            Prenom = "Baba",
                            ProfilId = 2,
                            TypeUtilisateurCode = "CLIENT"
                        },
                        new
                        {
                            Id = 7,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 632, DateTimeKind.Utc).AddTicks(80),
                            Email = "test7@test.com",
                            Nom = "Dédé",
                            Prenom = "Dédé",
                            ProfilId = 3,
                            TypeUtilisateurCode = "GEST"
                        },
                        new
                        {
                            Id = 8,
                            Actif = true,
                            DateCreation = new DateTime(2025, 10, 22, 15, 41, 30, 632, DateTimeKind.Utc).AddTicks(85),
                            Email = "test8@test.com",
                            Nom = "Ran",
                            Prenom = "Tanplan",
                            ProfilId = 4,
                            TypeUtilisateurCode = "ADMIN"
                        });
                });

            modelBuilder.Entity("KleeContrib.Dfta.Common.References.Securite.Droit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dro_code");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dro_libelle");

                    b.Property<string>("TypeDroitCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tdr_code");

                    b.HasKey("Code");

                    b.HasIndex("Libelle");

                    b.HasIndex("TypeDroitCode");

                    b.ToTable("droits");

                    b.HasData(
                        new
                        {
                            Code = "CREATE",
                            Libelle = "securite.droit.values.Create",
                            TypeDroitCode = "WRITE"
                        },
                        new
                        {
                            Code = "READ",
                            Libelle = "securite.droit.values.Read",
                            TypeDroitCode = "READ"
                        },
                        new
                        {
                            Code = "UPDATE",
                            Libelle = "securite.droit.values.Update",
                            TypeDroitCode = "WRITE"
                        },
                        new
                        {
                            Code = "DELETE",
                            Libelle = "securite.droit.values.Delete",
                            TypeDroitCode = "ADMIN"
                        });
                });

            modelBuilder.Entity("KleeContrib.Dfta.Common.References.Securite.TypeDroit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tdr_code");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tdr_libelle");

                    b.HasKey("Code");

                    b.HasIndex("Libelle");

                    b.ToTable("type_droits");

                    b.HasData(
                        new
                        {
                            Code = "READ",
                            Libelle = "securite.typeDroit.values.Read"
                        },
                        new
                        {
                            Code = "WRITE",
                            Libelle = "securite.typeDroit.values.Write"
                        },
                        new
                        {
                            Code = "ADMIN",
                            Libelle = "securite.typeDroit.values.Admin"
                        });
                });

            modelBuilder.Entity("KleeContrib.Dfta.Common.References.Securite.TypeUtilisateur", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tut_code");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tut_libelle");

                    b.HasKey("Code");

                    b.HasIndex("Libelle");

                    b.ToTable("type_utilisateurs");

                    b.HasData(
                        new
                        {
                            Code = "ADMIN",
                            Libelle = "securite.typeUtilisateur.values.Admin"
                        },
                        new
                        {
                            Code = "GEST",
                            Libelle = "securite.typeUtilisateur.values.Gestionnaire"
                        },
                        new
                        {
                            Code = "CLIENT",
                            Libelle = "securite.typeUtilisateur.values.Client"
                        });
                });

            modelBuilder.Entity("KleeContrib.Dfta.Clients.Db.Securite.Models.DroitProfil", b =>
                {
                    b.HasOne("KleeContrib.Dfta.Common.References.Securite.Droit", null)
                        .WithMany()
                        .HasForeignKey("DroitCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KleeContrib.Dfta.Clients.Db.Securite.Models.Profil", null)
                        .WithMany()
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KleeContrib.Dfta.Clients.Db.Securite.Models.Utilisateur", b =>
                {
                    b.HasOne("KleeContrib.Dfta.Clients.Db.Securite.Models.Profil", null)
                        .WithMany()
                        .HasForeignKey("ProfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KleeContrib.Dfta.Common.References.Securite.TypeUtilisateur", null)
                        .WithMany()
                        .HasForeignKey("TypeUtilisateurCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KleeContrib.Dfta.Common.References.Securite.Droit", b =>
                {
                    b.HasOne("KleeContrib.Dfta.Common.References.Securite.TypeDroit", null)
                        .WithMany()
                        .HasForeignKey("TypeDroitCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
